builds:
  - id: latency
    main: ./cmd/latency
    binary: latency
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0

release:
  github:
    owner: pintomau
    name: ringring

changelog:
  use: github-native
